"use client";

import { useMemo, useState } from "react";
import "./lesson-review.css";

type Strategy = "浠峰€兼垚闀? | "瓒嬪娍鎷╂椂" | "浣庢尝绾㈠埄";

const stocks = [
  { code: "600519", name: "璐靛窞鑼呭彴", sector: "娑堣垂", price: "1,462.00", change: "+1.18%", score: 91, tags: ["ROE", "鐜伴噾娴?] },
  { code: "300750", name: "瀹佸痉鏃朵唬", sector: "鏂拌兘婧?, price: "284.60", change: "+2.46%", score: 88, tags: ["鎴愰暱", "鍔ㄩ噺"] },
  { code: "601318", name: "涓浗骞冲畨", sector: "閲戣瀺", price: "46.72", change: "+0.71%", score: 84, tags: ["浣庝及", "绾㈠埄"] },
  { code: "000858", name: "浜旂伯娑?, sector: "娑堣垂", price: "128.31", change: "-0.32%", score: 79, tags: ["璐ㄩ噺", "浠峰€?] },
  { code: "688981", name: "涓姱鍥介檯", sector: "鍗婂浣?, price: "93.10", change: "+3.25%", score: 76, tags: ["瓒嬪娍", "绐佺牬"] },
];

const lessons = [
  { n: "01", title: "AI 杈呭姪鍐欑瓥鐣ワ細鍏堣窇閫氾紝鍐嶄慨閿?, desc: "璇嗗埆骞冲彴閿欓厤銆丄I 骞昏鍜屾渶灏忓彲杩愯闂幆", state: "宸茬湅瀹?, color: "mint" },
  { n: "02", title: "閲忓寲涓嶇瓑浜庨珮棰戯細鍏堟妸瑙勫垯鍐欐竻妤?, desc: "鐢ㄩ绠椼€佷环浣嶅拰浠撲綅鎶婃兂娉曞彉鎴愬彲澶嶇洏鐨勪氦鏄撹鍒?, state: "宸茬湅瀹?, color: "blue" },
  { n: "03", title: "绛栫暐涓嶆槸璧氶挶淇濊瘉锛氬厛鐞嗚В鍥炴挙涓庤繍琛屾鏋?, desc: "浠?QMT 鏈€灏忕瓥鐣ラ鏋跺紑濮嬶紝鐭ラ亾浠ｇ爜浣曟椂琚皟鐢?, state: "宸茬湅瀹?, color: "sand" },
  { n: "04", title: "璁?AI 璇绘噦鎶ラ敊锛氫粠鍙繍琛岀瓥鐣ュ埌瀹炵洏淇″彿", desc: "瀹氫綅鍙橀噺銆佹椂闂存潯浠跺拰淇″彿閾捐矾锛屽啀閫愭淇浠ｇ爜", state: "宸茬湅瀹?, color: "violet" },
  { n: "05", title: "浠庡崟鍙偂绁ㄥ埌鎵归噺閫夎偂锛氭暟鎹€佹潯浠朵笌寰幆", desc: "鐢ㄦ棩蹇楃‘璁よ鎯呮牸寮忥紝鍐嶆壂鎻忚偂绁ㄥ垪琛ㄥ鎵剧瓥鐣ヤ俊鍙?, state: "宸茬湅瀹?, color: "rose" },
  { n: "06", title: "AI 鐢熸垚绛栫暐鐨勫姣斿疄楠?, desc: "姣旇緝妯″瀷銆佸钩鍙板拰鎻愮ず涓婁笅鏂囷紝鍏堥獙璇佸啀鎵╁睍", state: "宸茬湅瀹?, color: "violet" },
  { n: "07", title: "绛栫暐瑕佹寔缁凯浠ｏ細浠庡洖娴嬪埌灏忚祫閲戝疄鐩?, desc: "鐞嗚В婊戠偣銆佹垚浜ら噺鍜岀淮鎶ゆ垚鏈紝鍒妸鍥炴祴褰撴壙璇?, state: "宸茬湅瀹?, color: "sand" },
  { n: "08", title: "鍏堝仛鍙繍琛岀殑灏忚疆瀛愶紝鍐嶇粍瑁呯瓥鐣?, desc: "姣旇緝 QMT銆丳Trade 涓庨€氳揪淇★紝骞跺鐞嗛噸澶嶄笅鍗曢闄?, state: "宸茬湅瀹?, color: "blue" },
  { n: "09", title: "浠庨浂鍐欑瓥鐣ワ細鍏堥獙璇?API锛屽啀鎺ュ叆鍩烘湰闈㈣繃婊?, desc: "鐢ㄨ偂涓滀汉鏁板嚱鏁版媶杞瓙锛岃繛鎺ュ弻鍧囩嚎涓庡洖娴嬫ā鎷?, state: "宸茬湅瀹?, color: "mint" },
];

const chart = [46, 52, 49, 57, 61, 59, 68, 73, 69, 78, 84, 91, 88, 96, 100];

export default function Home() {
  const [active, setActive] = useState("鎬昏");
  const [strategy, setStrategy] = useState<Strategy>("浠峰€兼垚闀?);
  const [running, setRunning] = useState(false);
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState<string[]>(["600519", "601318"]);

  const filteredStocks = useMemo(
    () => stocks.filter((stock) => `${stock.code}${stock.name}${stock.sector}`.includes(query.trim())),
    [query],
  );

  const toggleSaved = (code: string) => {
    setSaved((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]);
  };

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <div className="brand"><span className="brand-mark">鉄?/span><span>Alpha 鐮斾範绀?/span></div>
        <div className="workspace-pill"><span className="status-dot" />涓汉鐮旂┒鍙?span className="chevron">鈱?/span></div>
        <p className="nav-label">宸ヤ綔鍖?/p>
        <nav className="nav-list" aria-label="涓诲鑸?>
          {["鎬昏", "鑲＄エ绛涢€?, "鍥炴祴瀹為獙瀹?, "澶嶇洏璁板綍"].map((item) => (
            <button key={item} className={`nav-item ${active === item ? "active" : ""}`} onClick={() => setActive(item)}>
              <span className="nav-icon">{item === "鎬昏" ? "鈼? : item === "鑲＄エ绛涢€? ? "鈱? : item === "鍥炴祴瀹為獙瀹? ? "鈼? : "鈻?}</span>{item}
              {item === "鑲＄エ绛涢€? && <span className="nav-badge">12</span>}
            </button>
          ))}
        </nav>
        <p className="nav-label learn-label">瀛︿範涓庤祫鏂?/p>
        <nav className="nav-list">
          <button className={`nav-item ${active === "瀛︿範璺緞" ? "active" : ""}`} onClick={() => setActive("瀛︿範璺緞")}><span className="nav-icon">鈻?/span>鏁欑▼瀛︿範璺緞</button>
          <button className="nav-item"><span className="nav-icon">鈼?/span>鍥犲瓙搴?<span className="soon">Soon</span></button>
          <button className="nav-item"><span className="nav-icon">鈿?/span>鏁版嵁璁剧疆</button>
        </nav>
        <div className="sidebar-footer"><div className="avatar">L</div><div><strong>鏋楀悓瀛?/strong><span>鏈湴妯″紡 路 鏈悓姝?/span></div><span className="more">鈥⑩€⑩€?/span></div>
      </aside>

      <section className="main-panel">
        <header className="topbar">
          <div className="crumbs"><span>涓汉鐮旂┒鍙?/span><span>/</span><strong>{active}</strong></div>
          <div className="top-actions"><span className="market-status"><i /> 娌繁甯傚満 路 浜ゆ槗鏃?/span><button className="icon-button" aria-label="鎼滅储">鈱?/button><button className="icon-button" aria-label="閫氱煡">鈾?/button><button className="primary-button" onClick={() => setActive("鍥炴祴瀹為獙瀹?)}>锛?鏂板缓瀹為獙</button></div>
        </header>

        <div className="content">
          {active === "瀛︿範璺緞" ? <LearningPath /> : active === "鑲＄エ绛涢€? ? <Screener query={query} setQuery={setQuery} filteredStocks={filteredStocks} saved={saved} toggleSaved={toggleSaved} /> : active === "鍥炴祴瀹為獙瀹? ? <Backtest strategy={strategy} setStrategy={setStrategy} running={running} setRunning={setRunning} /> : <Overview onOpen={(item) => setActive(item)} strategy={strategy} setStrategy={setStrategy} running={running} setRunning={setRunning} />}
        </div>
      </section>
    </main>
  );
}

function Overview({ onOpen, strategy, setStrategy, running, setRunning }: { onOpen: (item: string) => void; strategy: Strategy; setStrategy: (value: Strategy) => void; running: boolean; setRunning: (value: boolean) => void }) {
  return <>
    <div className="hero-row"><div><p className="eyebrow">MONDAY 路 2026.08.24</p><h1>鎶婃瘡涓€娆″垽鏂紝<em>鍙樻垚鍙獙璇佺殑绛栫暐銆?/em></h1><p className="hero-copy">浠庢暀绋嬮噷鐨勭煡璇嗙偣锛屽埌浣犺嚜宸辩殑鐮旂┒缁撹銆傝繖閲屾槸涓€涓彧灞炰簬浣犵殑 A 鑲￠噺鍖栧伐浣滃彴銆?/p></div><div className="hero-actions"><button className="secondary-button" onClick={() => onOpen("瀛︿範璺緞")}>缁х画瀛︿範 <span>鈫?/span></button><button className="primary-button" onClick={() => onOpen("鑲＄エ绛涢€?)}>寮€濮嬮€夎偂 <span>鈫?/span></button></div></div>
    <div className="insight-card"><div className="insight-icon">鉁?/div><div><span className="card-kicker">浠婃棩鐮旂┒鎻愮ず 路 鍩轰簬鏁欑▼绗?37鈥?2 鑺?/span><h3>鍏堟帶鍒跺洖鎾わ紝鍐嶈拷姹傛敹鐩娿€?/h3><p>鎶婅川閲忋€佷及鍊煎拰瓒嬪娍鎷嗗紑瑙傚療锛岄伩鍏嶅彧鐢ㄥ崟涓€鎶€鏈寚鏍囧仛鍐冲畾銆?/p></div><button className="text-button" onClick={() => onOpen("鍥炴祴瀹為獙瀹?)}>鍘诲疄楠屽楠岃瘉 鈫?/button></div>
    <div className="section-heading"><div><p className="eyebrow">RESEARCH SNAPSHOT</p><h2>鐮旂┒姒傝</h2></div><span className="muted">鏁版嵁鏇存柊浜?08:56 路 绀轰緥鏁版嵁</span></div>
    <div className="metric-grid"><Metric label="绛栫暐缁勫悎鍑€鍊? value="1.284" delta="+28.4%" note="杩囧幓 12 涓湀" positive /><Metric label="鏈€澶у洖鎾? value="-8.7%" delta="鈫?2.1%" note="杈冧笂鏈堟敼鍠? positive /><Metric label="浠婃棩鍊欓€? value="12" delta="+4" note="绗﹀悎褰撳墠绛涢€夊櫒" positive /><Metric label="瀛︿範杩涘害" value="24 / 108" delta="22%" note="宸插畬鎴?24 涓珷鑺? /></div>
    <div className="dashboard-grid"><div className="panel performance-panel"><div className="panel-head"><div><p className="eyebrow">PORTFOLIO CURVE</p><h3>绛栫暐鍑€鍊艰蛋鍔?/h3></div><div className="segmented"><button className="selected">1Y</button><button>6M</button><button>1M</button></div></div><div className="chart-wrap"><div className="y-labels"><span>1.30</span><span>1.20</span><span>1.10</span><span>1.00</span></div><div className="bar-chart">{chart.map((height, index) => <div className="chart-col" key={index}><div className="bar" style={{ height: `${height}%` }} /><span>{index % 3 === 0 ? ["08/25", "11/25", "02/26", "05/26", "08/26"][index / 3] : ""}</span></div>)}</div></div><div className="chart-legend"><span><i className="legend-dot primary" />鎴戠殑缁勫悎 <strong>+28.4%</strong></span><span><i className="legend-dot gray" />娌繁 300 <strong className="dark">+11.6%</strong></span></div></div><div className="panel strategy-panel"><div className="panel-head"><div><p className="eyebrow">ACTIVE STRATEGY</p><h3>褰撳墠绛栫暐</h3></div><button className="dots">鈥⑩€⑩€?/button></div><div className="strategy-name"><span className="strategy-mark">鈼?/span><div><strong>{strategy}</strong><span>澶氬洜瀛?路 鍛ㄩ璋冧粨</span></div><span className="live-tag">杩愯涓?/span></div><div className="factor-list"><div><span>浠峰€煎洜瀛?/span><strong>30%</strong><div className="progress"><i style={{ width: "30%" }} /></div></div><div><span>璐ㄩ噺鍥犲瓙</span><strong>40%</strong><div className="progress"><i style={{ width: "40%" }} /></div></div><div><span>瓒嬪娍鍥犲瓙</span><strong>30%</strong><div className="progress"><i style={{ width: "30%" }} /></div></div></div><button className={`run-button ${running ? "running" : ""}`} onClick={() => { setRunning(true); setTimeout(() => setRunning(false), 1200); }}>{running ? "姝ｅ湪杩愯鍥炴祴鈥? : "杩愯涓€娆″洖娴?}<span>鈫?/span></button></div></div>
    <div className="section-heading lower"><div><p className="eyebrow">LEARNING PATH</p><h2>鏁欑▼ 鈫?宸ュ叿</h2></div><button className="text-button" onClick={() => onOpen("瀛︿範璺緞")}>鏌ョ湅瀹屾暣璺緞 鈫?/button></div>
    <div className="lesson-grid">{lessons.slice(0, 3).map((lesson) => <LessonCard key={lesson.n} lesson={lesson} />)}</div>
  </>;
}

function Metric({ label, value, delta, note, positive }: { label: string; value: string; delta: string; note: string; positive?: boolean }) { return <div className="metric-card"><span className="metric-label">{label}</span><strong>{value}</strong><div><span className={positive ? "up" : "neutral"}>{delta}</span><span className="metric-note">{note}</span></div></div>; }

function Screener({ query, setQuery, filteredStocks, saved, toggleSaved }: { query: string; setQuery: (value: string) => void; filteredStocks: typeof stocks; saved: string[]; toggleSaved: (code: string) => void }) { return <><div className="page-heading"><div><p className="eyebrow">STOCK SCREENER</p><h1>鑲＄エ绛涢€?/h1><p>鎶婃暀绋嬮噷鐨勫洜瀛愶紝缁勫悎鎴愪粖澶╁彲瑙ｉ噴鐨勫€欓€夋睜銆?/p></div><button className="primary-button">淇濆瓨绛涢€夊櫒</button></div><div className="filter-strip"><div className="search-field"><span>鈱?/span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="鎼滅储鑲＄エ浠ｇ爜銆佸悕绉版垨琛屼笟" /></div><span className="filter-chip">娌繁 A 鑲?脳</span><span className="filter-chip">ROE 鈮?15% 脳</span><span className="filter-chip">杩?20 鏃ュ姩閲?鈫?脳</span><button className="text-button">锛?娣诲姞鏉′欢</button></div><div className="screener-summary"><div><span>绗﹀悎鏉′欢</span><strong>{filteredStocks.length} <small>/ 5,218</small></strong></div><div><span>缁勫悎閫昏緫</span><strong>浠峰€?+ 璐ㄩ噺 + 瓒嬪娍</strong></div><div><span>璋冧粨棰戠巼</span><strong>姣忓懆涓€</strong></div></div><div className="table-panel"><div className="table-head"><h3>鍊欓€夎偂绁?/h3><span>鎺掑簭锛氱患鍚堣瘎鍒?鈫?/span></div><div className="stock-table"><div className="table-row table-header"><span>鑲＄エ</span><span>琛屼笟</span><span>鏈€鏂颁环</span><span>浠婃棩娑ㄨ穼</span><span>缁煎悎璇勫垎</span><span /></div>{filteredStocks.map((stock) => <div className="table-row" key={stock.code}><div className="stock-name"><button className={`star ${saved.includes(stock.code) ? "saved" : ""}`} onClick={() => toggleSaved(stock.code)} aria-label={`鏀惰棌 ${stock.name}`}>鈽?/button><div><strong>{stock.name}</strong><span>{stock.code}</span></div></div><span className="sector-pill">{stock.sector}</span><strong>{stock.price}</strong><span className={stock.change.startsWith("+") ? "up" : "down"}>{stock.change}</span><div className="score"><strong>{stock.score}</strong><div><i style={{ width: `${stock.score}%` }} /></div></div><button className="row-arrow">鈫?/button></div>)}</div></div></>; }

function Backtest({ strategy, setStrategy, running, setRunning }: { strategy: Strategy; setStrategy: (value: Strategy) => void; running: boolean; setRunning: (value: boolean) => void }) { return <><div className="page-heading"><div><p className="eyebrow">BACKTEST LAB</p><h1>鍥炴祴瀹為獙瀹?/h1><p>鎶婁竴涓兂娉曞彉鎴愪竴缁勮兘琚鐩樼殑鏁板瓧銆?/p></div><button className="primary-button" onClick={() => { setRunning(true); setTimeout(() => setRunning(false), 1400); }}>{running ? "杩愯涓€? : "杩愯鍥炴祴"}</button></div><div className="backtest-grid"><div className="panel config-panel"><div className="panel-head"><div><p className="eyebrow">CONFIGURATION</p><h3>瀹為獙璁剧疆</h3></div><span className="draft-tag">鑽夌</span></div><label>閫夋嫨绛栫暐</label><div className="strategy-options">{(["浠峰€兼垚闀?, "瓒嬪娍鎷╂椂", "浣庢尝绾㈠埄"] as Strategy[]).map((item) => <button key={item} className={strategy === item ? "selected" : ""} onClick={() => setStrategy(item)}>{item}<span>{item === "浠峰€兼垚闀? ? "澶氬洜瀛? : item === "瓒嬪娍鎷╂椂" ? "鎶€鏈寚鏍? : "鑲℃伅璐ㄩ噺"}</span></button>)}</div><div className="form-grid"><label>鍥炴祴鍖洪棿<select defaultValue="杩?3 骞?><option>杩?3 骞?/option><option>杩?5 骞?/option><option>鍏ㄥ巻鍙?/option></select></label><label>鍒濆璧勯噾<input defaultValue="100,000" /></label><label>璋冧粨鍛ㄦ湡<select defaultValue="鍛ㄩ"><option>鍛ㄩ</option><option>鏃ラ</option><option>鏈堥</option></select></label><label>鍗曠エ涓婇檺<input defaultValue="20%" /></label></div><div className="cost-row"><span>浜ゆ槗鎴愭湰</span><span>浣ｉ噾 0.03% 路 鍗拌姳绋?0.05% 路 婊戠偣 0.10%</span></div></div><div className="panel result-panel"><div className="panel-head"><div><p className="eyebrow">RESULT PREVIEW</p><h3>{strategy} 路 鍥炴祴缁撴灉</h3></div><span className="date-tag">2023.08 鈥?2026.08</span></div><div className="result-metrics"><div><span>绱鏀剁泭</span><strong className="up">+28.40%</strong></div><div><span>骞村寲鏀剁泭</span><strong>+9.03%</strong></div><div><span>鏈€澶у洖鎾?/span><strong className="down">-8.70%</strong></div><div><span>澶忔櫘姣旂巼</span><strong>1.42</strong></div></div><div className="mini-chart"><div className="mini-grid" />{chart.map((height, index) => <i key={index} style={{ height: `${height * .74}%` }} />)}</div><div className="result-footer"><span>鑳滅巼 58.3%</span><span>浜ゆ槗娆℃暟 86</span><span>鎹㈡墜鐜?112%</span><button className="text-button">鏌ョ湅瀹屾暣鎶ュ憡 鈫?/button></div></div></div><div className="callout"><span>鈸?/span><p>杩欐槸绀轰緥鍥炴祴缁撴灉锛屾帴鍏ョ湡瀹炶鎯呮暟鎹悗鎵嶄細璁＄畻鐪熷疄琛ㄧ幇銆傚巻鍙叉敹鐩婁笉浠ｈ〃鏈潵鏀剁泭銆?/p></div></>; }

function LearningPath() { return <><div className="page-heading"><div><p className="eyebrow">COURSE MAP</p><h1>鏁欑▼瀛︿範璺緞</h1><p>鎶?B 绔?108 闆嗚绋嬶紝鍘嬬缉鎴愪竴鏉¤兘鐪熸鍋氬嚭涓滆タ鐨勪釜浜鸿矾绾裤€?/p></div><div className="progress-ring"><strong>22%</strong><span>宸插畬鎴?/span></div></div><div className="course-note"><div className="course-avatar">B</div><div><strong>鍙傝€冭绋嬶細B绔?Python 瀹樻柟璧勬簮 路 閲忓寲浜ゆ槗鏁欑▼</strong><p>璇剧▼鐩綍瑕嗙洊鍩虹銆佹暟鎹垎鏋愩€佺瓥鐣ャ€侀€夎偂銆佹嫨鏃朵笌鍥炴祴锛涚綉绔欏彧鎻愮偧鏂规硶锛屼笉杞浇瑙嗛鍐呭銆?/p></div><a href="https://www.bilibili.com/video/BV1bXCTBGE42" target="_blank" rel="noreferrer">鎵撳紑鍘熻绋?鈫?/a></div><LessonReview /><LessonReviewTwo /><LessonReviewThree /><LessonReviewFour /><LessonReviewFive /><LessonReviewSix /><LessonReviewSeven /><LessonReviewEight /><LessonReviewNine /><JoinQuantReference /><div className="lesson-list">{lessons.map((lesson, index) => <div className={`lesson-row ${index === 8 ? "current" : ""}`} key={lesson.n}><div className={`lesson-number ${lesson.color}`}>{lesson.n}</div><div className="lesson-info"><strong>{lesson.title}</strong><span>{lesson.desc}</span></div><div className="lesson-status">{lesson.state}{index < 9 && <i />}</div><button className="row-arrow">鈫?/button></div>)}</div><div className="method-grid"><div><span>姣忚妭璇剧殑杈撳嚭</span><strong>涓€鏉″彲杩愯鐨勭爺绌剁瑪璁?/strong></div><div><span>姣忓懆鐨勫鐩?/span><strong>绛栫暐 路 浜ゆ槗 路 椋庨櫓涓夋爮</strong></div><div><span>鏈€缁堢洰鏍?/span><strong>褰㈡垚鑷繁鐨勬姇璧勬祦绋?/strong></div></div></>; }

function JoinQuantReference() { return <section className="joinquant-reference"><div className="joinquant-reference-head"><div><p className="eyebrow">JOINQUANT 路 DATA</p><h3>鑱氬鍘熸枃锛氫竷銆佹暟鎹幏鍙?/h3><p>浣滆€咃細buoyant 路 绾?3 骞村墠 路 鏂囩珷鍐呭惈鍥犲瓙鏁版嵁鑾峰彇銆佽储鍔℃寚鏍囥€佹妧鏈寚鏍囥€佺爺绌朵唬鐮佷笌杈撳嚭琛ㄦ牸銆?/p></div><a href="https://www.joinquant.com/view/community/detail/63c2508b996897cd0bdf2214dee9cde2" target="_blank" rel="noreferrer">鍦ㄨ仛瀹芥墦寮€ 鈫?/a></div><div className="joinquant-summary"><span className="review-label">杩欑瘒鏂囩珷鏀捐繘缃戠珯鐨勫師鍥?/span><p>瀹冩妸鈥滄暟鎹?鈫?鍥犲瓙 鈫?鍒嗘瀽 鈫?绛栫暐鈥濅覆璧锋潵锛屾槸鎶婂墠闈㈣绋嬩粠琛屾儏鏁版嵁鎺ㄨ繘鍒板熀鏈潰鐮旂┒鐨勯噸瑕佷竴璇俱€傞〉闈腑鐨勪唬鐮佸拰琛ㄦ牸淇濈暀鍦ㄤ笅闈㈢殑鍘熸枃绐楀彛閲岋紝鐐瑰嚮鍚庡彲浠ュ畬鏁存祻瑙堛€佸睍寮€浠ｇ爜鍜屾煡鐪嬭緭鍑恒€?/p><div className="joinquant-points"><span>璐㈠姟鍥犲瓙</span><span>閲忎环鍥犲瓙</span><span>鎶€鏈寚鏍?/span><span>鍥犲瓙鏈夋晥鎬у垎鏋?/span></div></div><div className="joinquant-frame-wrap"><iframe title="鑱氬鏂囩珷锛氫竷銆佹暟鎹幏鍙? src="https://www.joinquant.com/view/community/detail/63c2508b996897cd0bdf2214dee9cde2" loading="lazy" /></div><p className="joinquant-fallback">濡傛灉鍘熸枃绐楀彛琚祻瑙堝櫒鎷︽埅锛岃鐐瑰嚮鍙充笂瑙掆€滃湪鑱氬鎵撳紑鈥濓紱缃戠珯浠嶄繚鐣欎簡杩欑瘒鏂囩珷鐨勬潵婧愬拰瀛︿範绗旇銆?/p></section>; }

function LessonReview() { return <section className="lesson-review"><div className="review-head"><div><p className="eyebrow">LESSON 01 路 WATCHED</p><h3>AI 鑳藉府浣犲啓浠ｇ爜锛屼絾涓嶈兘鏇夸綘鍒ゆ柇浠ｇ爜</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>QMT銆丮iniQMT銆丳Trade 绛夊钩鍙扮殑鍑芥暟涓嶈兘娣风潃鐢ㄣ€?/li><li>鍏堟嬁涓€涓幇鎴愮瓥鐣ヨ窇閫氭鏋讹紝鍐嶉€愭澧炲姞瑙勫垯銆?/li><li>鎶ラ敊鏃跺厛鐪嬮敊璇銆佸嚱鏁版槸鍚﹀瓨鍦紝涓嶈璁?AI 涓€娆￠噸鍐欏嚑鐧捐銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑绀轰緥瑙勫垯</span><p>20 鏃ラ珮鐐瑰洖鎾?鈮?20%锛岃繛缁?3 澶╀笉鍒涙柊浣庡悗涔板叆锛涘啿楂?8% 涓斾粠楂樼偣鍥炶惤 4% 鍗栧嚭锛涗簭鎹?8% 姝㈡崯锛屾渶澶氭寔鏈?10 澶┿€?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">鏈€鏈変环鍊肩殑涓嶆槸杩欎簺鍙傛暟锛岃€屾槸鈥滃厛楠岃瘉妗嗘灦锛屽啀璁?AI 鏀瑰皬鍧椻€濈殑宸ヤ綔鏂规硶銆傚弬鏁板繀椤荤粡杩囧洖娴嬶紝涓嶈兘鐩存帴褰撴垚涔板崠寤鸿銆?/p></div></div></section>; }

function LessonReviewTwo() { return <section className="lesson-review lesson-review-blue"><div className="review-head"><div><p className="eyebrow">LESSON 02 路 WATCHED</p><h3>閲忓寲涓嶇瓑浜庨珮棰戯細鍏堟妸浠撲綅瑙勫垯鍐欐竻妤?/h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>閲忓寲鏄妸涓昏鍒ゆ柇鍐欐垚鍙墽琛岃鍒欙紝涓嶇瓑浜庡繀椤绘嫾浜ゆ槗閫熷害銆?/li><li>涓汉鎶曡祫鑰呭彲浠ヤ粠浣庨銆佸彲澶嶇洏鐨勮〃鏍肩瓥鐣ュ紑濮嬨€?/li><li>棰勭畻銆佷环鏍煎尯闂村拰鎸佷粨姣斾緥瑕佹彁鍓嶅啓濂斤紝鍑忓皯涓寸洏鍑劅瑙夋搷浣溿€?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑绀轰緥瑙勫垯</span><p>棰勮鎬婚绠楋紝璺熻釜绾?10鈥?0 鍙偂绁紱鎸変环鏍煎尯闂村垎閰嶄粨浣嶏紝涓婃定閫愮骇鍑忎粨銆佷笅璺岄€愮骇琛ヤ粨锛岃揪鍒版潯浠跺悗娓呬粨銆傚舰寮忓儚缃戞牸锛屼絾鍙互鑷繁璋冩暣姣忎竴妗ｃ€?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">杩欐洿鍍忊€滃崐鑷姩绾緥宸ュ叿鈥濓紝涓嶆槸鑷姩璧氶挶绯荤粺銆備笅璺岃ˉ浠撳繀椤昏鎬讳粨浣嶄笂闄愩€佸仠姝㈣ˉ浠撴潯浠跺拰鏈€澶у洖鎾わ紱AI 缁欏嚭鐨勮偂绁ㄥ悕鍗曞彧鑳藉仛鍊欓€夋睜锛岃繕瑕佽嚜宸辨牳楠屽熀鏈潰銆佹祦鍔ㄦ€у拰椋庨櫓鏍囩銆?/p></div></div></section>; }

function LessonReviewThree() { return <section className="lesson-review lesson-review-sand"><div className="review-head"><div><p className="eyebrow">LESSON 03 路 WATCHED</p><h3>鍏堢悊瑙ｅ洖鎾わ紝鍐嶅紑濮嬪啓绛栫暐</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>鎷垮埌涓€涓瓥鐣ワ紝涓嶄唬琛ㄦ嬁鍒扮ǔ瀹氭敹鐩婏紱鏈€澶у洖鎾ゅ喅瀹氫綘鑳戒笉鑳芥墰浣忔尝鍔ㄣ€?/li><li>绛栫暐鍙兘鍙€傚悎鏌愮甯傚満鐜锛岀墰甯傛湁鏁堜笉绛変簬鐔婂競涔熸湁鏁堛€?/li><li>QMT 鐨勬渶灏忛鏋跺彲浠ョ悊瑙ｄ负锛氬垵濮嬪寲涓€娆★紝鍐嶆寜涓?K 绾挎垨瀹氭椂鍑芥暟閲嶅鎵ц銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑杩愯閫昏緫</span><p>绋嬪簭浠庝笂鍒颁笅璇讳唬鐮侊紝鍏堟墽琛屽垵濮嬪寲鍑芥暟锛涗富鍑芥暟鎸夎瀹氬懆鏈熻璋冪敤锛屼緥濡傛寜 K 绾挎垨 Tick 瑙﹀彂锛岀劧鍚庝粠绗竴琛岃繍琛屽埌鏈€鍚庝竴琛屻€傜ず渚嬭繕灞曠ず浜嗘敞閲娿€佹妧鏈寚鏍囧拰涓嬫爣浠?0 寮€濮嬨€?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">杩欎竴鑺傜湡姝ｈ瀛︾殑鏄€滅瓥鐣ョ敓鍛藉懆鏈熲€濓紝涓嶆槸鑳屽嚱鏁板悕銆備笂绾垮墠瑕佸厛纭璋冪敤棰戠巼銆佹暟鎹槸鍚﹀畬鏁淬€佽鍗曟槸鍚﹂噸澶嶏紝浠ュ強鍥炴挙杈惧埌澶氬皯灏辨殏鍋滐紱杞欢鎶ラ敊鎴栧崱姝绘椂锛屼篃涓嶈兘鎶婄粨鏋滆璁や负绛栫暐澶辨晥鎴栨湁鏁堛€?/p></div></div></section>; }

function LessonReviewFour() { return <section className="lesson-review lesson-review-violet"><div className="review-head"><div><p className="eyebrow">LESSON 04 路 WATCHED</p><h3>鎶婃姤閿欏彉鎴愮嚎绱紝鑰屼笉鏄 AI 涔辨敼浠ｇ爜</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>鍏堢湅瀹屾暣鎶ラ敊鍜岃鍙凤紝鍐嶅垽鏂槸鍙橀噺銆佽处鍙风粦瀹氥€佹椂闂存潯浠惰繕鏄钩鍙版帴鍙ｉ棶棰樸€?/li><li>鎵句竴涓兘杩愯鐨勭瓥鐣ヤ綔涓哄熀鍑嗭紝璁板綍姣忔鏀瑰姩锛屽埆涓€涓婃潵閲嶅啓鏁村浠ｇ爜銆?/li><li>瀹炵洏鈥滆繍琛屼簡鈥濅笉绛変簬浜х敓浜嗕氦鏄撲俊鍙凤紝杩樿妫€鏌ヤ氦鏄撴椂闂村拰淇″彿閾捐矾銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑鎺掗敊杩囩▼</span><p>鎶?QMT 鐨勯敊璇俊鎭鍒剁粰 AI锛屽畾浣嶅埌鏈畾涔夊彉閲忥紱纭璇ュ彉閲忓師鏈緷璧栫晫闈㈢粦瀹氬悗锛屽厛鍒犻櫎鎴栨浛鎹㈣繖娈典緷璧栵紝鍐嶇敤鍙繍琛岀殑鑲＄エ璐﹀彿娴嬭瘯銆傞殢鍚庢鏌?09:30鈥?5:00 鐨勪氦鏄撴椂闂达紝瑙ｉ噴涓轰粈涔堝噷鏅ㄨ繍琛屼笉浼氫骇鐢熶俊鍙枫€?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">AI 鏈€閫傚悎鍋氣€滈敊璇炕璇戝櫒鈥濆拰鎺掓煡鍔╂墜锛屼笉閫傚悎鏇夸綘鐚滃钩鍙扮幆澧冦€傛瘡娆′慨澶嶉兘瑕佷繚鐣欐渶灏忔敼鍔ㄣ€佸鐜版楠ゅ拰鏃ュ織锛涙病鏈夋棩蹇楀氨鏃犳硶鍒ゆ柇绛栫暐鍒板簳鏈夋病鏈夎蛋鍒颁笅鍗曞垎鏀€?/p></div></div></section>; }

function LessonReviewFive() { return <section className="lesson-review lesson-review-rose"><div className="review-head"><div><p className="eyebrow">LESSON 05 路 WATCHED</p><h3>鍏堢‘璁ゆ暟鎹紝鍐嶈鏉′欢鍜屽惊鐜湡姝ｈ窇璧锋潵</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>鏃х増绛栫暐鍙兘鍥犱负鍘嗗彶琛屾儏鎺ュ彛鎴栬繑鍥炴牸寮忓彉鍖栬€屾棤娉曠洿鎺ヨ繍琛屻€?/li><li>鐢ㄦ墦鍗版棩蹇楃‘璁ゆ暟鎹槸鍚︽嬁鍒般€佸瓧娈垫牸寮忔槸鍚﹀尮閰嶏紝鍐嶇户缁帓鏌ユ潯浠躲€?/li><li>浠庡崟鍙偂绁ㄦ墿灞曞埌鑲＄エ鍒楄〃鏃讹紝瑕佺敤寰幆閫愪釜妫€鏌ワ紝鑰屼笉鏄鍒剁矘璐村嚑鍗侀亶銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑瀹炴搷閫昏緫</span><p>鍏堜慨姝ｅ巻鍙叉暟鎹幏鍙栵紝鎵撳嵃鍑鸿鎯呭悗妫€鏌ュ弻鍧囩嚎鏉′欢锛氬揩绾夸笂绌挎參绾挎墠涔板叆锛屽弽鍚戞墠鍗栧嚭銆傞殢鍚庢妸涓€涓浐瀹氬搧绉嶆敼鎴愭垚鍒嗚偂鍒楄〃锛屽惊鐜鎵炬弧瓒虫潯浠剁殑鑲＄エ锛屽啀鐢熸垚绛栫暐淇″彿銆?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">鈥滄病鏈変俊鍙封€濅笉绛変簬浠ｇ爜閿欎簡锛屽彲鑳藉彧鏄潯浠舵病鏈夋弧瓒筹紱浣嗕负浜嗘紨绀鸿€屾斁瀹芥潯浠讹紝涔熶笉鑳藉綋鎴愮瓥鐣ヤ紭鍖栥€傛壒閲忔壂鎻忓叏 A 鑲″墠锛岃繕瑕佽€冭檻鏁版嵁閲忋€佽繍琛岄€熷害銆佸仠鐗?娑ㄨ穼鍋滃拰閲嶅涓嬪崟銆?/p></div></div></section>; }

function LessonReviewSix() { return <section className="lesson-review lesson-review-violet"><div className="review-head"><div><p className="eyebrow">LESSON 06 路 WATCHED</p><h3>AI 鑳藉啓鍑虹ず渚嬶紝浣嗗钩鍙板拰涓婁笅鏂囧喅瀹氳兘涓嶈兘杩愯</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>鍚屼竴鍙モ€滃啓涓€涓弻鍧囩嚎绛栫暐鈥濓紝涓嶅悓 AI 鍙兘鐢熸垚涓嶅悓骞冲彴銆佷笉鍚屾帴鍙ｇ殑浠ｇ爜銆?/li><li>PTrade 璧勬枡鍜屾牱渚嬫洿澶氭椂锛孉I 鍙兘鏇村鏄撶敓鎴愬彲杩愯鐗堟湰锛涜繖涓嶄唬琛ㄥ畠澶╃劧鏇村ソ銆?/li><li>QMT / MiniQMT / PTrade 鐨勬鏋躲€佹暟鎹帴鍙ｅ拰鐗堟湰涓嶈兘娣风敤銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑瀵规瘮瀹為獙</span><p>鐢ㄨ眴鍖呫€佸厓瀹濄€佸崈闂€丏eepSeek 绛夋ā鍨嬬洿鎺ョ敓鎴?QMT 鍙屽潎绾跨瓥鐣ワ紝鍐嶅皾璇曞洖娴嬨€傜粨鏋滄樉绀猴細鏈夌殑浠ｇ爜绗竴琛屽氨閿欙紝鏈夌殑璋冪敤浜嗛敊璇鏋讹紝鏈夌殑鍥犱负鏈嶅姟鍣ㄨ祫婧愰檺鍒舵棤娉曡窇鍒嗛挓鏁版嵁銆?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">AI 涓嶆槸鈥滆緭鍏ヤ竴鍙ヨ瘽灏辫嚜鍔ㄥ畬鎴愰噺鍖栤€濄€傛彁闂椂蹇呴』鍐欐竻骞冲彴鐗堟湰銆丄PI銆佹暟鎹簮銆佽处鍙枫€佸懆鏈熷拰鐩爣锛涚敓鎴愬悗瑕佸厛妫€鏌ユ暟鎹槸鍚︾湡鐨勮繘鏉ワ紝鍐嶅仛鍥炴祴銆傛ā鍨嬬増鏈洿鏂板緢蹇紝瀹樻柟鏂囨。鍜屾渶灏忓彲杩愯鏍蜂緥姣旀ā鍨嬭嚜淇″洖绛旀洿鍙潬銆?/p></div></div></section>; }

function LessonReviewSeven() { return <section className="lesson-review lesson-review-sand"><div className="review-head"><div><p className="eyebrow">LESSON 07 路 WATCHED</p><h3>鍥炴祴鍙槸绛涢€夛紝鐪熷疄鎴愪氦鎵嶆槸妫€楠?/h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>AI 鏄緟鍔╁伐鍏凤紝涓嶆槸鎶婁氦鏄撳畬鍏ㄤ氦缁欐満鍣ㄧ殑鎸夐挳銆?/li><li>鎵句汉鍐欑瓥鐣ヤ笉鏄竴娆′氦浠橈紝鍚庣画缁存姢銆佽凯浠ｅ拰鐭ヨ瘑浜ゆ帴鎵嶆槸闀挎湡鎴愭湰銆?/li><li>涓€涓瓥鐣ヨ缁忓巻鍥炴祴銆佹ā鎷熺洏銆佸皬璧勯噾瀹炵洏锛屼笉鑳借烦杩囬獙璇侀樁娈点€?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑楠岃瘉娴佺▼</span><p>鍏堢敤鍘嗗彶鍖洪棿鍥炴祴锛屽啀鐢ㄦā鎷熻祫閲戣繍琛屼竴娈垫椂闂达紝鏈€鍚庡彧鐢ㄥ皯閲忚祫閲戝疄鐩樻祴璇曘€傚洖娴嬨€佹ā鎷熷拰瀹炵洏缁撴灉涓嶄竴鑷村緢姝ｅ父锛屽洜涓虹湡瀹炴垚浜や細鍙椾环鏍笺€佹垚浜ら噺銆佽鍗曡妯″拰婊戠偣褰卞搷銆?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">涓嶈杩蜂俊楂樻敹鐩婂洖娴嬨€傛粦鐐瑰簲鍦ㄥ洖娴嬩腑浣滀负鏇翠繚瀹堢殑鎴愪氦鍋囪锛岀洰鐨勬槸璁╃粨鏋滄帴杩戠幇瀹烇紱瀹炵洏鍒欒鍏虫敞鎴愪氦鐜囥€佸啿鍑绘垚鏈拰浠撲綅瑙勬ā銆傜瓥鐣ヨ繕蹇呴』鑳芥寔缁凯浠ｏ紝鍚﹀垯甯傚満鐜涓€鍙樺氨浼氬け鏁堛€?/p></div></div></section>; }

function LessonReviewEight() { return <section className="lesson-review lesson-review-blue"><div className="review-head"><div><p className="eyebrow">LESSON 08 路 WATCHED</p><h3>鍏堝仛鑳借窇鐨勫皬鍔熻兘锛屽啀鎷兼垚瀹屾暣绛栫暐</h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>鎶婁拱鍏ャ€佸崠鍑恒€佸彇鏁版嵁绛夊姛鑳藉垎鍒仛鎴愬彲楠岃瘉鐨勫皬鈥滆疆瀛愨€濓紝鍐嶇粍瑁呮垚绛栫暐銆?/li><li>鍚屾牱鐨勫潎绾块€昏緫锛屽湪 QMT銆丳Trade銆侀€氳揪淇￠噷鐨勪唬鐮佸舰寮忓拰鑷敱搴︿笉鍚屻€?/li><li>骞冲彴瓒婄伒娲伙紝浠ｇ爜鍜屽涔犳垚鏈€氬父瓒婇珮锛涘叕寮忓钩鍙扮畝鍗曞揩閫燂紝浣嗗彲鍋氱殑浜嬫儏鏇村皯銆?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑瀹炵洏缁嗚妭</span><p>鍧囩嚎绛栫暐瑕佸垽鏂€滃彂鐢熶笂绌库€濊€屼笉鏄彧鍒ゆ柇鈥滃綋鍓嶅揩绾垮ぇ浜庢參绾库€濓紝鍚﹀垯鏉′欢鍙兘鎸佺画鎴愮珛銆備笅鍗曞悗杩樿妫€鏌ユ湭鎴愪氦濮旀墭锛屼笉鑳藉彧鐪嬫寔浠擄紱缃戠粶鎴栨湇鍔″欢杩熸椂锛岄噸澶嶄笅鍗曞彲鑳介€犳垚瓒呴浠撲綅銆?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">鏈€灏忓彲杩愯鏍蜂緥鏄法骞冲彴瀛︿範鐨勫熀鍑嗐€傛棤璁虹敤鍝釜骞冲彴锛岄兘瑕佹妸鏁版嵁銆佷俊鍙枫€佹寔浠撱€佸鎵樺拰鎴愪氦鐘舵€佸垎寮€璁板綍锛屽苟缁欎笅鍗曢€昏緫鍔犲箓绛変繚鎶わ紱鈥滀唬鐮佸緢鐭€佹壂鎻忓緢蹇€濅笉绛変簬瀹炵洏鏇村畨鍏ㄣ€?/p></div></div></section>; }

function LessonReviewNine() { return <section className="lesson-review lesson-review-rose"><div className="review-head"><div><p className="eyebrow">LESSON 09 路 WATCHED</p><h3>鍏堣瘉鏄?API 瀛樺湪锛屽啀璁?AI 甯綘鎺ョ瓥鐣?/h3></div><span className="review-tag">鎴戠殑鎬濊€?/span></div><div className="review-columns"><div><span className="review-label">杩欒妭璇捐娓呮浜?/span><ul><li>浠庣┖鐧?QMT 绛栫暐寮€濮嬫椂锛屽厛鐢ㄥ畼鏂?API 鏂囨。纭鍑芥暟锛岄槻姝?AI 缂栭€犳帴鍙ｃ€?/li><li>鎶娾€滆幏鍙栬偂涓滀汉鏁扳€濆崟鐙仛鎴愪竴涓彲杩愯鐨勮疆瀛愶紝鍐嶆帴鍏ュ弻鍧囩嚎鏉′欢銆?/li><li>璐㈠姟鏁版嵁闇€瑕佸厛涓嬭浇锛岀己鏁版嵁鏃剁粨鏋滀负绌轰笉涓€瀹氭槸浠ｇ爜閿欍€?/li></ul></div><div><span className="review-label">瑙嗛閲岀殑瀹炴搷娴佺▼</span><p>鍏堝彇涓€鍙偂绁ㄧ殑鑲′笢浜烘暟锛屽彂鐜版暟鎹负绌哄悗涓嬭浇璐㈠姟鏁版嵁锛屽苟琛ヤ笂鏌ヨ鏃ユ湡锛屾渶缁堝緱鍒板巻鍙茶偂涓滀汉鏁般€傞殢鍚庡彲浠ユ壂鎻忔垚鍒嗚偂/鍏?A 鑲★紝鎸夎偂涓滀汉鏁扮瓑鏉′欢杩囨护锛屽啀鍥炴祴鍙屽潎绾跨瓥鐣ワ紱鍥炴祴鏃跺幓鎺夆€滆烦杩囧巻鍙?K 绾库€濈殑瀹炵洏閫昏緫銆?/p><span className="review-label">鎴戠殑鍒ゆ柇</span><p className="review-opinion">鑲′笢浜烘暟杩欑被璐㈠姟鏁版嵁蹇呴』鎸夊綋鏃跺彲鑾峰緱鐨勬棩鏈熷榻愶紝涓嶈兘鎶婁粖澶╃殑鏁版嵁鎷垮幓绛涢€夎繃鍘汇€傚洖娴嬫病鏈変氦鏄撴椂锛岃鍗曠嫭璺戜竴涓棩鏈熷拰涓€鍙偂绁ㄣ€佸噺灏戞墦鍗帮紝鍐嶆牳瀵硅祫閲戙€佹暟閲忋€佷俊鍙峰拰涓嬪崟鍑芥暟锛涙ā鎷熺洏鍒欒鍖哄垎淇″彿 鈫?濮旀墭 鈫?鎴愪氦 鈫?鎸佷粨锛屽苟闄愬畾 09:30鈥?5:00銆?/p></div></div></section>; }

function LessonCard({ lesson }: { lesson: (typeof lessons)[number] }) { return <div className="lesson-card"><div className={`lesson-number ${lesson.color}`}>{lesson.n}</div><div><span className="lesson-state">{lesson.state}</span><h3>{lesson.title}</h3><p>{lesson.desc}</p></div><span className="card-arrow">鈫?/span></div>; }

